name: ia_triagem
description: Questionario de Pisicopatologia

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6'


dependencies:
  flutter:
    sdk: flutter  
  just_audio: ^0.9.34
  audioplayers: ^4.1.0
  flutter_colorpicker: ^1.0.3        
  flutter_modular: ^5.0.3
  hive: ^2.2.3
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0  
  http: ^0.13.5
  card_settings:
    path: assets/card_settings
  brasil_fields: ^1.13.1
  intl: ^0.18.1
  pattern_formatter: ^3.0.0
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/assinatura_resia.png
    - assets/assinatura_keiji.png
    - assets/arvore_free.png
    - assets/olho1.png
    - assets/olho2.png
    - assets/olho3.png
    - assets/olho4.png
    - assets/olho5.png
    - assets/olho6.png
    - assets/olho7.png
    - assets/olho8.png
    - assets/olho9.png
    - assets/olho10.png
    - assets/olho11.png
    - assets/olho12.png
    - assets/olho13.png
    - assets/olho14.png                                
    - assets/intel_1.png
    - assets/intel_1a.png
    - assets/intel_1b.png
    - assets/intel_1c.png
    - assets/intel_1d.png
    - assets/intel_1e.png
    - assets/intel_1f.png
    - assets/questao32.png
    - assets/Ebbinghaus.png
    - assets/questao45leao.png
    - assets/questao45coquetel.png
    - assets/questao45passaro.png
    - assets/questao45gato.png
    - assets/questao45cachorro.png
    - assets/questao45bombons.png
    - assets/questao45cafe.png
    - assets/questao45carro.png
    - assets/questao45casa.png
    - assets/questao45cerveja.png
    - assets/questao45cocacola.png
    - assets/questao45humburgue.png
    - assets/questao45passaro.png
    - assets/audios/aguacorrente-edited_v2.mp3
    - assets/audios/chuva_edited.mp3
    - assets/audios/chuva.mp3
    - assets/audios/chuva_edited.wav
    - assets/audios/quatro_palavras.mp3
    - assets/audios/dez_palavras.mp3
    - assets/AI_1.jpg
    - assets/coracao_free.png
    - assets/casa_free.png
    - assets/rosa_free.png
    - assets/intel_2.png
    - assets/intel_2a.png
    - assets/intel_2b.png
    - assets/intel_2c.png
    - assets/intel_2d.png
    - assets/intel_2e.png
    - assets/intel_2f.png
    - assets/intel_4.png
    - assets/intel_4a.png
    - assets/intel_4b.png
    - assets/intel_4c.png
    - assets/intel_4d.png
    - assets/intel_4e.png
    - assets/intel_4f.png
    - assets/teste_logica_3.png
    - assets/emotion1.png
    - assets/emotion2.png
    - assets/emotion3.png
    - assets/emotion4.png
    - assets/emotion5.png
    - assets/emotion6.png
    - assets/five_errors1.jpg
    - assets/five_errors2.jpg
    - assets/pontos.jpg
    - assets/ponte_free.jpg
    - assets/car.png
    - assets/moto_free.png
    - assets/leao_free.png
    - assets/passaro_free.png
    - assets/motorcycle_free.png
    - assets/cat_free.png
    - assets/cachorro_free.png

