name: ia_triagem
description: Questionario de Pisicopatologia

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6'


dependencies:
  flutter:
    sdk: flutter  
  just_audio: ^0.9.33
  flutter_colorpicker: ^1.0.3        
  flutter_modular: ^5.0.3
  card_settings:
    path: assets/card_settings
  brasil_fields: ^1.13.1
  intl: ^0.18.1
  pattern_formatter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/assinatura_resia.png
    - assets/assinatura_keiji.png
    - assets/audios/aguacorrente-edited_v2.mp3
    - assets/audios/chuva_edited.mp3
    - assets/audios/chuva.mp3
    - assets/audios/chuva_edited.wav
    - assets/audios/quatro_palavras.mp3
    - assets/audios/dez_palavras.mp3
    - assets/AI_1.jpg
    - assets/arvore_free.png
    - assets/coracao_free.png
    - assets/casa_free.png
    - assets/rosa_free.png
    - assets/intel_1.png
    - assets/intel_1a.png
    - assets/intel_1b.png
    - assets/intel_1c.png
    - assets/intel_1d.png
    - assets/intel_1e.png
    - assets/intel_1f.png
    - assets/intel_2.png
    - assets/intel_2a.png
    - assets/intel_2b.png
    - assets/intel_2c.png
    - assets/intel_2d.png
    - assets/intel_2e.png
    - assets/intel_2f.png
    - assets/intel_4.png
    - assets/intel_4a.png
    - assets/intel_4b.png
    - assets/intel_4c.png
    - assets/intel_4d.png
    - assets/intel_4e.png
    - assets/intel_4f.png
    - assets/teste_logica_3.png
    - assets/emotion1.png
    - assets/emotion2.png
    - assets/emotion3.png
    - assets/emotion4.png
    - assets/emotion5.png
    - assets/emotion6.png
    - assets/five_errors1.jpg
    - assets/five_errors2.jpg
    - assets/pontos.jpg
    - assets/ponte_free.jpg
    - assets/car.png
    - assets/moto_free.png
    - assets/leao_free.png
    - assets/passaro_free.png
    - assets/motorcycle_free.png
    - assets/cat_free.png
    - assets/cachorro_free.png
    - assets/Ebbinghaus.png
