on: [push, pull_request]
name: Test Package
jobs:
  test:
    name: Run tests on the package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - name: Install flutter dependencies
        run: flutter pub get
      - name: Install packages dependencies
        run: flutter packages get
      - name: Run tests with coverage
        run: flutter test --coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
